### ISSUE TITLE
Zenodo license options dropdown

### ISSUE THREAD

**Issue by sblack-usu** [cznethub/dsp#20]
**Describe the feature you'd like and what it will do**
zenodo.org has a dropdown for license choices.  The license options are from https://opendefinition.org/.  Data Submission Portal should allow license choices in the same way.  This will require a component to be developed that can use their API.

https://opendefinition.org/licenses/api/

**Why is this feature important?**
It is a lot easier to find and correctly identify a license

**Is your feature request related to a problem? Please describe.**
It is difficult to correctly find and set a license identifier with just a string.

**Additional context**
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/35820390/156677793-f3373a48-7e5f-491d-aeb4-ee73d16f9fd2.png">

**Comment by horsburgh** [comment]
@sblack-usu - I'm curious how you got that screen shot. When I go to production Zenodo, I can only choose from a list of Creative Commons Attribution licenses:

![image](https://user-images.githubusercontent.com/3485902/156799574-7e950d0f-b622-451e-bcf0-4b493dde183f.png)

Given this, I'm not sure it's worth building something in instead of just using the Creative Commons Attribution 4.0 International license.

This is also weird because their guidance text below the license picker states: 

> If you cannot find the license you're looking for, include a relevant LICENSE file in your record and choose one of the Other licenses available (Other (Open), Other (Attribution), etc.). The supported licenses in the list are harvested from [opendefinition.org ](https://opendefinition.org/) and [spdx.org ](https://spdx.org/). If you think that a license is missing from the list, please [contact us](https://zenodo.org/support).

There are no "Other" licenses available in their drop down list.

**Comment by sblack-usu** [comment]
There is a much longer list of licenses that you can search for `Start typing a license name` and other options will be listed.

**Comment by horsburgh** [comment]
Huh. OK, I missed the whole "Start Typing" thing because when I clicked on the box it was a drop down with only a few options available and I assumed that I could only choose from the items in the list. Shannon also made the same assumption. Also, the drop down is slow to respond, you have to wait long enough for something different to pop up. In any case, the way this box works in Zenodo isn't ideal because it presumes that a user knows what's in the list and can start typing it in.

I see why the API call is important now, but let's make it easier for users to figure out which licenses they can choose from.

**Comment by Maurier** [comment]
What's left to do from this issue is an update of the labels so that they are more descriptive.

**Comment by Maurier** [comment]
Descriptive license titles have been added to the current items in our schema. Pending implementation of renderer that can read from the api as described.

**Comment by Maurier** [comment]
We are going to grab a snapshot of the json file and serve it as part of our schema. This way we keep a schema driven approach. We will update these data as needed.
