### ISSUE TITLE
Do we need a confirmation on delete?

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#88]
**Describe the feature you'd like and what it will do**

When a user chooses to delete an entry from their My Submissions page, they can choose an option to also try and delete from the remote repository. However, when they click the "DELETE" link, the delete happens immediately. Do we want to have a confirmation that they really want to delete. I only ask because we have had issues with people "accidentally" deleting things from HydroShare when we didn't have a confirmation like this.

**Why is this feature important?**

To avoid accidental deletions.

**Is your feature request related to a problem? Please describe.**

No - this is a feature/enhancement.

**Additional context**

N/A

**Comment by Maurier** [comment]
I think the pop up window already serves as confirmation. However, the checkbox state is currently persisted between sessions, and users might fail to uncheck it (after checking it prior) for resources they intend to keep in the repository.

We could instead remove it from persistent state, and always initially show it unchecked when the pop up opens, so that they explicitly have to check it in order to attempt to delete from the repository.

**Comment by horsburgh** [comment]
@Maurier - As a minimum, I like your suggestion. That box should only be checked if a user specifically checks it.

**Comment by Maurier** [comment]
The checkbox state has now been removed from persistent state. This change will be reflected in the next testing deployment.

**Comment by Maurier** [comment]
The adjustments to checkbox state have been implemented.
